### ISSUE TITLE
인덱서와 섹션의 Text 칼라 중복 오류

### ISSUE THREAD

**Issue by ditongs** [WindSekirun/KoreanIndexerListView#5]
setSectionTextColor 함수안에서 textPaint의 값을 변경하기 때문에 설정에 문제가 발견되었습니다.

**Comment by WindSekirun** [comment]
문제 제기 감사드립니다. 
현재 b47fd9d07df9a64b971bf58f399b75912b666925 기준으로 setSectionTextColor가 sectionTextPaint 의 색상 값을 변경하도록 변경하였습니다.

단, 이와 관련되지 않은 다른 부분의 이슈가 있기에 당분간은 릴리즈 되지 않을 예정입니다.

**Comment by WindSekirun** [comment]
그래서, 프로젝트의 의존 설정 부분에 현 1.1.0 대신  compile 'com.github.WindSekirun:KoreanIndexerListView:-SNAPSHOT' 을 사용하시면 적용된 버전을 바로 사용하실 수 있습니다.
